src/pages/tutorials/data-entities.md, src/pages/tutorials/prior.md
Converted data-entities.html and priors.html to markdown and added them to the tutorials section in /src
@mcdonnelldean @geek
=> added in prior.md and data-entities.md to the tutorials section

src/pages/contribute/_contributing.md
copied the contribute.md file from Nanite, changed the wording to suit Senecas.org and other small changes like removing a section. 
@mcdonnelldean @geek
=> added in _contributing.md into contribute folder

src/template/layouts/splash.html
links were pointing to wrong sites, fixed all the links.
@mcdonnelldean @geek
=> fixed links for companies using Seneca

src/template/layouts/main.html
added in a link to report issues. I'm going to look at some others to see if we can make it more fun and get people more interested in reporting any issue they find.
@mcdonnelldean @geek
=> added in link to report issues

src/stylesheets/style.css
=> fixed images left aligning in mobile view

build.js, package.json, src/pages/404.md
Resolves https://github.com/senecajs/senecajs.org/issues/60
=> Added a custom 404 page

src/pages/plugins/index.md
* Added links to all plugins with presence on GitHub and NPM from https://github.com/search?p=1&q=seneca+transport&type=Repositories&utf8=%E2%9C%93
=> Plugins edit

src/pages/get-started/index.md
Related to https://github.com/senecajs/senecajs.org/issues/73 & https://github.com/rjrodger/seneca-transport/issues/37
=> Getting started: Added a note on the default host on windows

src/pages/tutorials/understanding-data-entities.md
Added API sections for documenting the `.canon$()` and `.data$()` methods for entities which I found useful when developing plugins.
=> Entity API: .canon$() and .data$()

src/pages/tutorials/how-to-write-a-plugin.md
=> Added correct in page links

src/stylesheets/style.css, src/template/layouts/splash.html, src/template/partials/head.html, src/template/partials/menu.html
I changed both the header and body fonts. I left the SenecA as is, it's best to talk to Agata to design a new logo.
=> changed the fonts throughout the site

src/stylesheets/style.css, src/template/layouts/splash.html, src/template/partials/head.html
the header font reflects more of a romanesque theme, changed some wording back to original @mcdonnelldean @orlacoding
=> changed fonts to something more inline with site theme

src/pages/get-started/index.md
{ "answer":2} to 3
First, the listening service (math-plugin.js): ti math-pin-client.js
=> Minor doc edits

src/pages/tutorials/index.md
[Trello Card](https://trello.com/c/1ibEuzwv/62-senecajs-org-general-tidy-with-more-emphasis-on-examples)
=> General tidy with more emphasis on examples

src/pages/annotations/seneca.html, src/pages/support/index.md, src/pages/tutorials/how-to-write-a-plugin.md, src/pages/tutorials/index.md, src/pages/tutorials/logging-with-seneca.md, src/pages/tutorials/understanding-data-entities.md, src/pages/tutorials/understanding-prior-actions.md
* changes instances of rjrodger/seneca to senecajs/seneca
=> Link changes 1

src/pages/404.md, src/stylesheets/style.css, src/template/layouts/error.html
- Added a new template for errors with body class "error".
- Added error  styles in CSS
- Removed inline style in 404 page
=> [#62] Add error template with improved styles

src/pages/get-started/index.md
Fixed a typo in the code `src/pages/get-started/index.md`
=> Fixed a typo in the code

src/pages/tutorials/understanding-data-entities.md
Update link in *Understanding Data Entities*
=> Fixing some broken url link

package.json, src/pages/contribute/index.md, src/pages/contributors/index.md
* Added contributors page
* Added link to contributors page
=> Contributors

src/pages/api/index.md
=> Disable broken link.

metalsmith.json, package.json
=> Fix broken build

metalsmith.json, package.json, src/scss/style.scss
Basic Sass/scss setup. :)
(with liv-reload, it's just magic)
=> Setup scss

src/template/layouts/splash.html
Pending approval from @mcdonnelldean and @AdrieanKhisbe
Resolves #155
=> Removed beat-your-manager image from splash.

src/pages/contribute/details/code-of-conduct.md, src/pages/contribute/index.md
=> Added Chakra CoC, tidy work on /Contribute

src/pages/api/index.md
https://github.com/senecajs/senecajs.org/issues/170
I'm open to suggestions. The remainder will be done tomorrow.
=> Export and Pin API docs

src/pages/api/index.md
https://github.com/senecajs/senecajs.org/issues/170
I'm open to suggestions. Feel free to merge as You find appropriate.
=> Further API Docs

src/pages/api/index.md, src/pages/tutorials/how-to-write-a-plugin.md
https://github.com/senecajs/senecajs.org/issues/164
Also https://github.com/senecajs/seneca/pull/329
=> Add docs for plugin init

src/pages/tutorials/index.md, src/pages/tutorials/understanding-query-syntax.md
https://github.com/senecajs/senecajs.org/issues/53
I'm open to suggestions :)
Should I update https://github.com/senecajs/seneca/tree/master/doc/examples with source?
=> Add list$ docs

src/pages/contributors/index.md
https://github.com/senecajs/senecajs.org/issues/189
:)
=> Add Kamil to contributors

src/pages/api/index.md
=> Alphabetized API page

README.md
=> Update Naomi to Lead Maintainer

src/pages/roadmap.md
this is the beginning of a roadmap for future releases.
needs more explanatory language
=> add roadmap

metalsmith.json, package.json, src/pages/api/index.md, src/pages/get-started/index.md, src/pages/tutorials/understanding-data-entities.md, src/scss/components/type.scss, src/scss/globals/variables.scss, src/template/layouts/splash.html
- Corrected section glyph
- Major changes to api doc
- Updated surge version
- Various theme fixes
- corrections in entity document
- corrections in getting started document
=>  See below,

src/pages/api/index.md
just a few punctuation things. changing a "who" to "which" and using some semicolons.
=> Tiny punctuation tweaks

src/pages/api/index.md
=> fix API bookmarks

src/pages/api/index.md
Reverts senecajs/senecajs.org#260
=> Revert "fix API bookmarks"

src/pages/getting-started/index.md
=> Update Getting Started doc to fix broken link

src/pages/plugins/index.md
fully tested plugin for the latest version of CouchDb; requires minimal db setup
=> added seneca-couch2-store to docs, fixed link to senecajs.org

src/pages/docs/index.md
=> Fix small typo in index.md

src/pages/plugins/index.md
Seneca plugin for Seraph Library to connect a Neo4j Database.
=> Add Seraph Neo4j plugin

src/pages/docs/tutorials/unit-testing.md
=> Updated unit testing

.gitignore, src/pages/plugins/index.md
I just separated some lines, to correct markdown syntax.
=> Solution for issue #322

src/pages/plugins/index.md
I have published an MQTT Transport plugin working in NPM
=> Add MQTT Transport plugin
